import { useEffect, useState } from 'react'
import { api, ApiError } from '../services/api'
import type { InviteResponse, User } from '../types'
import { Button, Notice, Spinner } from '../components/UI'

export function AdminView({ currentUser }: { currentUser: User }) {
  const [users, setUsers] = useState<User[]>([]); const [invite, setInvite] = useState<InviteResponse | null>(null)
  const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [busyId, setBusyId] = useState<number | null>(null)
  const [apiOnline, setApiOnline] = useState(true)
  async function load() { setLoading(true); setError(''); try { setUsers(await api.users()); setApiOnline(true) } catch (err) { setApiOnline(false); setError(err instanceof ApiError ? err.message : 'Nie udało się pobrać użytkowników.') } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  async function role(user: User, next: User['role']) { setBusyId(user.id); setError(''); try { await api.setRole(user.id, next); await load() } catch (err) { setError(err instanceof Error ? err.message : 'Nie udało się zmienić roli.') } finally { setBusyId(null) } }
  async function remove(user: User) { if (!window.confirm(`Usunąć konto ${user.username}?`)) return; setBusyId(user.id); try { await api.deleteUser(user.id); await load() } catch (err) { setError(err instanceof Error ? err.message : 'Nie udało się usunąć użytkownika.') } finally { setBusyId(null) } }
  async function newInvite() { setError(''); try { setInvite(await api.createInvite()) } catch (err) { setError(err instanceof Error ? err.message : 'Nie udało się wygenerować zaproszenia.') } }
  return <section className="page-view"><div className="page-heading admin-heading"><div><span className="eyebrow">CENTRUM KONTROLI</span><h1>Administracja</h1><p>Zarządzaj dostępem do swojego systemu Auti.</p></div><Button onClick={()=>void newInvite()}>＋ Zaproś użytkownika</Button></div>{error && <Notice>{error}</Notice>}{invite && <div className="invite-banner"><div><span className="eyebrow">KOD ZAPROSZENIA • WAŻNY 24 GODZINY</span><b>{invite.code}</b></div><Button variant="ghost" onClick={()=>void navigator.clipboard.writeText(invite.code)}>Kopiuj kod</Button></div>}
    <div className="stats-grid"><article className="panel stat-card"><span className="stat-icon purple">♙</span><span className="eyebrow">UŻYTKOWNICY</span><b>{loading ? '—' : users.length}</b><small>konta w systemie</small></article><article className="panel stat-card"><span className="stat-icon green">✳</span><span className="eyebrow">ADMINISTRATORZY</span><b>{loading ? '—' : users.filter((u)=>u.role === 'admin').length}</b><small>z dostępem zarządczym</small></article><article className="panel stat-card"><span className="stat-icon amber">⌁</span><span className="eyebrow">API</span><b className="api-status"><i style={{background: apiOnline ? undefined : '#c84f56'}}/> {apiOnline ? 'Połączone' : 'Niedostępne'}</b><small>status bieżącego żądania</small></article></div>
    <article className="panel users-panel"><div className="users-panel-heading"><div><span className="eyebrow">DOSTĘP DO SYSTEMU</span><h2>Użytkownicy</h2></div><span className="users-count">{users.length} kont</span></div>{loading ? <Spinner label="Pobieranie listy"/> : users.length === 0 ? <p className="muted empty-copy">Brak kont użytkowników.</p> : <div className="table-wrap"><table><thead><tr><th>UŻYTKOWNIK</th><th>ROLA</th><th>DATA URODZENIA</th><th>AKCJE</th></tr></thead><tbody>{users.map((user)=><tr key={user.id}><td><div className="table-user"><span className="mini-avatar">{user.preferred_name.slice(0,1).toUpperCase()}</span><span><b>{user.preferred_name}</b><small>@{user.username}</small></span></div></td><td><select aria-label={`Rola ${user.username}`} disabled={busyId === user.id || user.id === currentUser.id} value={user.role} onChange={(e)=>void role(user,e.target.value as User['role'])}><option value="user">Użytkownik</option><option value="admin">Administrator</option></select></td><td>{user.date_of_birth || '—'}</td><td>{user.id === currentUser.id ? <span className="you-label">To Ty</span> : <button className="delete-row" disabled={busyId === user.id} onClick={()=>void remove(user)} aria-label={`Usuń ${user.username}`}>Usuń</button>}</td></tr>)}</tbody></table></div>}</article><p className="admin-note">Lista i zarządzanie kontami są pobierane bezpośrednio z API Auti.</p></section>
}
