import { useState, type FormEvent } from 'react'
import { useNavigate } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'
import { ApiError } from '../services/api'
import { Brand, Button, Input, Notice, PasswordInput } from '../components/UI'

const steps = ['Twoje dane', 'Połączenia', 'Gotowe']
export function OnboardingView() {
  const { finishSetup, initialized, user } = useAuth(); const navigate = useNavigate()
  const [step, setStep] = useState(0); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const [data, setData] = useState({ username: '', password: '', preferred_name: '', date_of_birth: '', gemini_api_key: '', info_for_ai: '' })
  function field(key: keyof typeof data) { return { value: data[key], onChange: (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => setData((old) => ({ ...old, [key]: e.target.value })) } }
  async function submit(e: FormEvent) { e.preventDefault(); if (step < 2) { setStep(step + 1); return }; setBusy(true); setError(''); try { await finishSetup({ ...data, gemini_api_key: data.gemini_api_key || null, info_for_ai: data.info_for_ai || null }); navigate('/chat') } catch (err) { setError(err instanceof ApiError ? err.message : 'Nie udało się zakończyć konfiguracji.') } finally { setBusy(false) } }
  return <main className="onboarding-page"><header><Brand/><span className="eyebrow">KONFIGURACJA AUTI</span></header><div className="onboarding-card"><span className="eyebrow">{user ? 'DOSTOSUJ SWOJE AUTI' : 'PIERWSZE URUCHOMIENIE'}</span><h1>{user ? 'Dokończmy konfigurację' : 'Zacznijmy od Ciebie.'}</h1><p className="muted">Kilka prostych kroków i Twój inteligentny dom będzie gotowy.</p><div className="stepper">{steps.map((name, i)=><div className={`step ${i <= step ? 'active' : ''}`} key={name}><span>{i < step ? '✓' : `0${i+1}`}</span><small>{name}</small></div>)}</div>{error && <Notice>{error}</Notice>}
    <form onSubmit={submit}>{step === 0 && <div className="form-grid"><Input label="Preferowane imię" {...field('preferred_name')} required/><Input label="Data urodzenia" type="date" {...field('date_of_birth')} required/><Input label="Nazwa użytkownika" {...field('username')} required minLength={2}/><PasswordInput label="Hasło" {...field('password')} required minLength={6}/></div>}
    {step === 1 && <div className="integrations"><div className="integration-card"><span className="integration-icon">✦</span><div><b>Klucz Gemini <span className="optional-label">OPCJONALNIE</span></b><p>Dodaj własny klucz Gemini. Możesz też skonfigurować go później.</p></div><PasswordInput label="Klucz Gemini API" {...field('gemini_api_key')} placeholder="Opcjonalnie"/></div><div className="integration-card"><span className="integration-icon home-icon">⌂</span><div><b>Home Assistant</b><p>Połączenie z Home Assistantem jest zarządzane po stronie serwera Auti.</p></div><span className="connected-tag"><i/> Serwer</span></div><label className="field"><span>Informacje dla AI <span className="optional-label">OPCJONALNIE</span></span><textarea rows={3} {...field('info_for_ai')} placeholder="Dodaj preferencje lub kontekst dla asystenta"/></label></div>}
    {step === 2 && <div className="ready-state"><div className="ready-icon">✦</div><h2>Wszystko gotowe, {data.preferred_name || 'przyjacielu'}.</h2><p>Twoje konto administratora zostanie utworzone, a Auti będzie gotowe do działania.</p><div className="ready-summary"><span>Rola <b>Administrator</b></span><span>Asystent AI <b>{data.gemini_api_key ? 'Skonfigurowany' : 'Do skonfigurowania'}</b></span><span>Home Assistant <b>Połączenie serwera</b></span></div></div>}
    <div className="wizard-actions">{step > 0 && <Button type="button" variant="ghost" onClick={()=>setStep(step-1)}>← Wstecz</Button>}<Button type="submit" disabled={busy || (initialized === true && !user)}>{busy ? 'Konfiguruję…' : step === 2 ? 'Utwórz konto i przejdź dalej' : 'Kontynuuj'}<span>→</span></Button></div></form>
    {initialized === true && !user && <Notice>Konfiguracja pierwszego konta jest już zakończona.</Notice>}</div><footer className="auth-legal">Twoje dane pozostają prywatne <span>•</span> Auti Home Assistant</footer></main>
}
