import { useState, type FormEvent } from 'react'
import { api, ApiError } from '../services/api'
import { useAuth } from '../context/AuthContext'
import { Button, Input, Notice } from '../components/UI'

export function ProfileView() {
  const { user, reloadUser, signOut } = useAuth()
  const [birth, setBirth] = useState(user?.date_of_birth ?? ''); const [aiInfo, setAiInfo] = useState(user?.info_for_ai ?? '')
  const [apiKey, setApiKey] = useState(''); const [notice, setNotice] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  async function save(e: FormEvent) { e.preventDefault(); setBusy(true); setError(''); setNotice(''); try { await api.updateBirthDate(birth); await api.updateProfile({ info_for_ai: aiInfo, ...(apiKey ? { gemini_api_key: apiKey } : {}) }); await reloadUser(); setApiKey(''); setNotice('Zmiany zostały zapisane.') } catch (err) { setError(err instanceof ApiError ? err.message : 'Nie udało się zapisać zmian.') } finally { setBusy(false) } }
  async function deleteAccount() { if (!window.confirm('Czy na pewno chcesz trwale usunąć swoje konto? Tej operacji nie można cofnąć.')) return; try { await api.deleteAccount(); await signOut() } catch (err) { setError(err instanceof Error ? err.message : 'Nie udało się usunąć konta.') } }
  return <section className="page-view"><div className="page-heading"><span className="eyebrow">USTAWIENIA</span><h1>Twój profil</h1><p>Ustawienia konta i preferencje asystenta.</p></div><div className="profile-grid"><article className="panel profile-identity"><div className="profile-avatar">{(user?.preferred_name || user?.username || 'A').slice(0,1).toUpperCase()}</div><h2>{user?.preferred_name}</h2><span className="muted">@{user?.username}</span><span className={`role-tag ${user?.role === 'admin' ? 'admin-tag' : ''}`}>{user?.role === 'admin' ? 'Administrator' : 'Użytkownik'}</span><div className="identity-meta"><span>Aktywne konto</span><b><i/> Połączono</b></div><Button variant="ghost" onClick={()=>void signOut()}>Wyloguj się <span>↗</span></Button></article>
    <article className="panel profile-settings"><div className="panel-title"><div><span className="eyebrow">DANE KONTA</span><h2>Personalizacja</h2></div><span className="subtle-icon">✳</span></div>{error && <Notice>{error}</Notice>}{notice && <Notice tone="success">{notice}</Notice>}<form onSubmit={save}><Input label="Nazwa wyświetlana" value={user?.preferred_name ?? ''} readOnly/><Input label="Data urodzenia" type="date" value={birth} onChange={(e)=>setBirth(e.target.value)}/><div className="setting-divider"/><Input label="Klucz Gemini API" type="password" autoComplete="new-password" value={apiKey} onChange={(e)=>setApiKey(e.target.value)} placeholder="Pozostaw puste, aby nie zmieniać"/><label className="field"><span>Preferencje asystenta</span><textarea rows={4} value={aiInfo} onChange={(e)=>setAiInfo(e.target.value)} placeholder="Co Auti powinno wiedzieć o Twoim domu?"/></label><Button type="submit" disabled={busy}>{busy ? 'Zapisywanie…' : 'Zapisz zmiany'}<span>→</span></Button></form></article></div><article className="panel danger-zone"><div><b>Usuń konto</b><small>Trwale usuń swoje konto i sesje. Ta czynność jest nieodwracalna.</small></div><Button variant="danger" onClick={()=>void deleteAccount()}>Usuń konto</Button></article></section>
}
